# Worksheet 0 - A Tutorial and Assessment on Python and NumPy


## Task 1: Unit Conversion

In [16]:
def convert_units():
    """
    Converts between different units of measurement.

    Returns:
        None
    """
    print("Choose conversion type:")
    print("1. Length (meters <-> feet)")
    print("2. Weight (kilograms <-> pounds)")
    print("3. Volume (liters <-> gallons)")

    try:
        choice = int(input("Enter 1, 2, or 3: "))

        if choice == 1:
            value = float(input("Enter value: "))
            unit = input("Enter current unit (m/ft): ").lower()
            if unit == 'm':
                print(f"{value} meters = {value * 3.28084} feet")
            elif unit == 'ft':
                print(f"{value} feet = {value / 3.28084} meters")
            else:
                print("Invalid unit.")

        elif choice == 2:
            value = float(input("Enter value: "))
            unit = input("Enter current unit (kg/lbs): ").lower()
            if unit == 'kg':
                print(f"{value} kg = {value * 2.20462} lbs")
            elif unit == 'lbs':
                print(f"{value} lbs = {value / 2.20462} kg")
            else:
                print("Invalid unit.")

        elif choice == 3:
            value = float(input("Enter value: "))
            unit = input("Enter current unit (L/gal): ").lower()
            if unit == 'l':
                print(f"{value} liters = {value * 0.264172} gallons")
            elif unit == 'gal':
                print(f"{value} gallons = {value / 0.264172} liters")
            else:
                print("Invalid unit.")

        else:
            print("Invalid choice.")

    except ValueError:
        print("Invalid input. Please enter numerical values.")

convert_units()




Choose conversion type:
1. Length (meters <-> feet)
2. Weight (kilograms <-> pounds)
3. Volume (liters <-> gallons)
Enter 1, 2, or 3: 3
Enter value: 5
Enter current unit (L/gal): 4
Invalid unit.


## Task 2: Mathematical Operations

In [17]:
def calculate():
    """
    Performs various mathematical operations on a list of numbers.

    Returns:
        None
    """
    try:
        numbers = list(map(float, input("Enter numbers separated by spaces: ").split()))
        if not numbers:
            raise ValueError("List is empty.")

        print("Choose operation:")
        print("1. Sum")
        print("2. Average")
        print("3. Maximum")
        print("4. Minimum")

        choice = int(input("Enter 1, 2, 3, or 4: "))

        if choice == 1:
            print(f"Sum: {sum(numbers)}")
        elif choice == 2:
            print(f"Average: {sum(numbers) / len(numbers)}")
        elif choice == 3:
            print(f"Maximum: {max(numbers)}")
        elif choice == 4:
            print(f"Minimum: {min(numbers)}")
        else:
            print("Invalid choice.")

    except ValueError as e:
        print(f"Error: {e}")

calculate()


Enter numbers separated by spaces: 5
Choose operation:
1. Sum
2. Average
3. Maximum
4. Minimum
Enter 1, 2, 3, or 4: 4
Minimum: 5.0


## Task 3: List Manipulations

In [20]:
def extract_every_other(lst):
    return lst[::2]
def get_sublist(lst, start, end):
    return lst[start:end+1]
def reverse_list(lst):
    return lst[::-1]
def remove_first_last(lst):
    return lst[1:-1]
def get_first_n(lst, n):
    return lst[:n]
def get_last_n(lst, n):
    return lst[-n:]
def reverse_skip(lst):
    return lst[-2::-2]



In [23]:
# Exapmle usage
lst = [1, 2, 3, 4, 5, 6]
print("every other element:",extract_every_other(lst))
print("sublist(2,4):",get_sublist(lst, 2,4))
print("reversed list:",reverse_list(lst))
print("without first and last:",remove_first_last(lst))
print("first 3:",get_first_n(lst, 3))
print("last 3:",get_last_n(lst, 2))
print("reverse skip:",reverse_skip(lst))

every other element: [1, 3, 5]
sublist(2,4): [3, 4, 5]
reversed list: [6, 5, 4, 3, 2, 1]
without first and last: [2, 3, 4, 5]
first 3: [1, 2, 3]
last 3: [5, 6]
reverse skip: [5, 3, 1]


## Task 4: Nested List Operations

In [40]:
def flatten(lst):
    """Recursively flattens a nested list."""
    return [item for sublist in lst for item in (flatten(sublist) if isinstance(sublist, list) else [sublist])]

def access_nested_element(lst, indices):
    """Accesses an element in a nested list using a list of indices."""
    for index in indices:
        lst = lst[index]
    return lst

def nested_sum(lst):
    """Computes the sum of all elements in a nested list."""
    return sum(flatten(lst))

def remove_element(lst, element):
    """Removes all occurrences of a specific element from a nested list."""
    return [[x for x in sublist if x != element] for sublist in lst]

def find_max(lst):
    """Finds the maximum element in a nested list."""
    return max(flatten(lst))

def count_occurrences(lst, element):
    """Counts occurrences of an element in a nested list."""
    return flatten(lst).count(element)

def average_nested(lst):
    """Computes the average of all elements in a nested list."""
    flat = flatten(lst)
    return sum(flat) / len(flat) if flat else 0  # Avoid division by zero

# Example usage
nested_lst = [[1, 2], [3, [4, 5]], 6]
print("Flattened list:", flatten(nested_lst))
print("Accessing [1, 2]:", access_nested_element([[1, 2, 3], [4, 5, 6], [7, 8, 9]], [1, 2]))
print("Sum of elements:", nested_sum(nested_lst))
print("Remove 2:", remove_element([[1, 2], [3, 2], [4, 5]], 2))
print("Max element:", find_max(nested_lst))
print("Count 2:", count_occurrences([[1, 2], [2, 3], [2, 4]], 2))
print("Average:", average_nested([[1, 2], [3, 4], [5, 6]]))


Flattened list: [1, 2, 3, 4, 5, 6]
Accessing [1, 2]: 6
Sum of elements: 21
Remove 2: [[1], [3], [4, 5]]
Max element: 6
Count 2: 3
Average: 3.5


## NumPy Exercises

### Task 1: Creating and Manipulating NumPy Arrays

In [30]:
import numpy as np

# Creating arrays
arr_1d = np.array([1, 2, 3, 4, 5])
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
arr_zeros = np.zeros((2, 3))
arr_ones = np.ones((3, 2))
arr_random = np.random.rand(3, 3)

print("1D Array:")
print(arr_1d)
print("2D Array:")
print(arr_2d)
print("Zeros Array:")
print(arr_zeros)
print("Ones Array:")
print(arr_ones)
print("Random Array:")
print(arr_random)


# Reshaping an array
reshaped_arr = arr_1d.reshape(5,1)
print("Reshaped 1D Array:")
print(reshaped_arr)

# Accesing elements
print("element at (0,1):", arr_2d[0, 1])
print("first row:", arr_2d[0])
print("second column:", arr_2d[:, 1])

1D Array:
[1 2 3 4 5]
2D Array:
[[1 2 3]
 [4 5 6]]
Zeros Array:
[[0. 0. 0.]
 [0. 0. 0.]]
Ones Array:
[[1. 1.]
 [1. 1.]
 [1. 1.]]
Random Array:
[[0.08771405 0.6243725  0.34866424]
 [0.99991328 0.21184052 0.90129005]
 [0.39024734 0.61467418 0.13861642]]
Reshaped 1D Array:
[[1]
 [2]
 [3]
 [4]
 [5]]
element at (0,1): 2
first row: [1 2 3]
second column: [2 5]


### Task 2: NumPy Array Operations

In [31]:
#arithmetic operations
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("a + b:", a + b)
print("a - b:", a - b)
print("a * b:", a * b)
print("a / b:", a / b)

#Universal functions
print("Exponential:", np.exp(a))
print("Square root:", np.sqrt(a))
print("Logarithm:", np.log(a))

# Linear algebra operations
matrix_A = np.array([[1, 2], [3, 4]])
matrix_B = np.array([[5, 6], [7, 8]])

print("Dot Product:", np.dot(matrix_A, matrix_B))
print("Inverse of A:", np.linalg.inv(matrix_A))
print("Determinant of A:", np.linalg.det(matrix_A))

a + b: [5 7 9]
a - b: [-3 -3 -3]
a * b: [ 4 10 18]
a / b: [0.25 0.4  0.5 ]
Exponential: [ 2.71828183  7.3890561  20.08553692]
Square root: [1.         1.41421356 1.73205081]
Logarithm: [0.         0.69314718 1.09861229]
Dot Product: [[19 22]
 [43 50]]
Inverse of A: [[-2.   1. ]
 [ 1.5 -0.5]]
Determinant of A: -2.0000000000000004


### Task 3: Slicing and Indexing

In [32]:
#Slicing in 1D array
arr = np.array([10, 20, 30, 40, 50])
print("first three elements:", arr[:3])
print("last two elements:", arr[-2:])
print("every other element:", arr[::2])

#Slicing in 2D array
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("First two rows:", arr_2d[:2, :])
print("Last column:", arr_2d[:, -1])

first three elements: [10 20 30]
last two elements: [40 50]
every other element: [10 30 50]
First two rows: [[1 2 3]
 [4 5 6]]
Last column: [3 6]


### Task 4: Broadcasting

In [33]:
#Broadcasting exapmle
A = np.array([[1], [2], [3]])
B = np.array([10, 20, 30])
C = A + B
print("Broadcasting result:", C)

Broadcasting result: [[11 21 31]
 [12 22 32]
 [13 23 33]]


### Task 5: Error Handling in NumPye



In [34]:
# Handling index errors
arr = np.array([1, 2, 3])
try:
    print( arr[5]) # This will cause an error
except IndexError as e:
    print("Indexerror",e)

# Handling shape errors
try:
    a = np.array([1, 2, 3])
    b = np.array([[4, 5], [6, 7]])
    print(a + b)  # This will cause an error
except ValueError as e:
    print("ValueError:", e)


Indexerror index 5 is out of bounds for axis 0 with size 3
ValueError: operands could not be broadcast together with shapes (3,) (2,2) 


Numpy Speed Test


In [35]:
import time
import numpy as np


In [36]:
# 1. Element-wise Addition
size = 1_000_000
list1 = list(range(size))
list2 = list(range(size))

start_time = time.time()
result_list = [list1[i] + list2[i] for i in range(size)]
end_time = time.time()
print(f"Python List Addition Time: {end_time - start_time:.5f} seconds")

array1 = np.arange(size)
array2 = np.arange(size)

start_time = time.time()
result_array = array1 + array2
end_time = time.time()
print(f"NumPy Array Addition Time: {end_time - start_time:.5f} seconds")

Python List Addition Time: 0.18819 seconds
NumPy Array Addition Time: 0.01899 seconds


In [37]:
# 2. Element-wise Multiplication
start_time = time.time()
result_list = [list1[i] * list2[i] for i in range(size)]
end_time = time.time()
print(f"Python List Multiplication Time: {end_time - start_time:.5f} seconds")

start_time = time.time()
result_array = array1 * array2
end_time = time.time()
print(f"NumPy Array Multiplication Time: {end_time - start_time:.5f} seconds")

Python List Multiplication Time: 0.19376 seconds
NumPy Array Multiplication Time: 0.02334 seconds


In [38]:
# 3. Dot Product
start_time = time.time()
dot_product = sum(list1[i] * list2[i] for i in range(size))
end_time = time.time()
print(f"Python List Dot Product Time: {end_time - start_time:.5f} seconds")

start_time = time.time()
dot_product = np.dot(array1, array2)
end_time = time.time()
print(f"NumPy Array Dot Product Time: {end_time - start_time:.5f} seconds")

Python List Dot Product Time: 0.09584 seconds
NumPy Array Dot Product Time: 0.00183 seconds


In [39]:
# 4. Matrix Multiplication
matrix_size = 1000
matrix1 = [[i * j for j in range(matrix_size)] for i in range(matrix_size)]
matrix2 = [[i + j for j in range(matrix_size)] for i in range(matrix_size)]

start_time = time.time()
result_matrix = [[sum(matrix1[i][k] * matrix2[k][j] for k in range(matrix_size)) for j in range(matrix_size)] for i in range(matrix_size)]
end_time = time.time()
print(f"Python List Matrix Multiplication Time: {end_time - start_time:.5f} seconds")

np_matrix1 = np.array(matrix1)
np_matrix2 = np.array(matrix2)

start_time = time.time()
result_np_matrix = np.dot(np_matrix1, np_matrix2)
end_time = time.time()
print(f"NumPy Array Matrix Multiplication Time: {end_time - start_time:.5f} seconds")

Python List Matrix Multiplication Time: 200.36746 seconds
NumPy Array Matrix Multiplication Time: 1.27328 seconds
